# Each question tuple: (name, leetcode_number, link, difficulty, technique, hint/beta)

SEED_TOPICS = [
    {
        "name": "Arrays",
        "questions": [
            ("Two Sum", "1", "https://leetcode.com/problems/two-sum/", "Easy", "Hash Map",
             "Store each value's index in a hash map as you scan; check for its complement before inserting."),
            ("Best Time to Buy and Sell Stock", "121", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy", "Single Pass",
             "Track the lowest price seen so far and the best profit found while scanning left to right."),
            ("Maximum Subarray", "53", "https://leetcode.com/problems/maximum-subarray/", "Medium", "Kadane's Algorithm",
             "Keep a running sum and reset it to zero whenever it goes negative, tracking the max along the way."),
            ("Merge Sorted Array", "88", "https://leetcode.com/problems/merge-sorted-array/", "Easy", "Two Pointers (from the end)",
             "Fill the array back-to-front with three pointers so you never overwrite unmerged elements."),
            ("Remove Duplicates from Sorted Array", "26", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "Easy", "Two Pointers",
             "A slow pointer marks the next unique slot; a fast pointer scans ahead for the next new value."),
            ("Rotate Array", "189", "https://leetcode.com/problems/rotate-array/", "Medium", "Reversal Trick",
             "Reverse the whole array, then reverse the two segments split at index k."),
            ("Product of Array Except Self", "238", "https://leetcode.com/problems/product-of-array-except-self/", "Medium", "Prefix / Suffix Products",
             "Build prefix products left-to-right, then multiply in suffix products right-to-left."),
            ("Majority Element", "169", "https://leetcode.com/problems/majority-element/", "Easy", "Boyer–Moore Voting",
             "Track a candidate and a counter — increment on a match, decrement otherwise, swap candidates at zero."),
            ("Move Zeroes", "283", "https://leetcode.com/problems/move-zeroes/", "Easy", "Two Pointers",
             "Track where the next non-zero should land while scanning past the zeroes."),
            ("Contains Duplicate", "217", "https://leetcode.com/problems/contains-duplicate/", "Easy", "Hash Set",
             "Insert into a set as you go; the first repeat you hit is your answer."),
            ("Find the Missing Number", "268", "https://leetcode.com/problems/missing-number/", "Easy", "Sum Formula / XOR",
             "Compare the expected sum of 0..n to the actual sum, or XOR every index against every value."),
            ("Find All Numbers Disappeared in an Array", "448", "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/", "Easy", "Index Marking",
             "Negate the value at the index each number points to; unmarked indices are your missing numbers."),
            ("Sort Colors", "75", "https://leetcode.com/problems/sort-colors/", "Medium", "Dutch National Flag",
             "Use low/mid/high pointers to partition 0s, 1s, and 2s in a single pass."),
            ("Next Permutation", "31", "https://leetcode.com/problems/next-permutation/", "Medium", "In-place Rearrangement",
             "Find the first drop from the right, swap it with the next larger value after it, then reverse the tail."),
            ("Trapping Rain Water", "42", "https://leetcode.com/problems/trapping-rain-water/", "Hard", "Two Pointers",
             "Track the max height seen from each side; move the pointer on the shorter side inward."),
            ("Container With Most Water", "11", "https://leetcode.com/problems/container-with-most-water/", "Medium", "Two Pointers",
             "Start at the widest span and always move the pointer at the shorter line."),
            ("Gas Station", "134", "https://leetcode.com/problems/gas-station/", "Medium", "Greedy",
             "If total gas ≥ total cost a route exists — reset your start whenever the running tank drops below zero."),
            ("Jump Game", "55", "https://leetcode.com/problems/jump-game/", "Medium", "Greedy",
             "Track the farthest index reachable so far; if you reach a gap you can't cross, it's impossible."),
            ("Jump Game II", "45", "https://leetcode.com/problems/jump-game-ii/", "Medium", "Greedy (BFS-like layers)",
             "Track the current jump's boundary and the farthest reach; add a jump each time you cross the boundary."),
            ("Candy", "135", "https://leetcode.com/problems/candy/", "Hard", "Two-Pass Greedy",
             "Pass left-to-right enforcing the right-neighbor rule, then right-to-left enforcing the left-neighbor rule."),
        ],
    },
    {
        "name": "Strings",
        "questions": [
            ("Valid Anagram", "242", "https://leetcode.com/problems/valid-anagram/", "Easy", "Frequency Count",
             "Count character frequencies in both strings (or sort both) and compare."),
            ("Valid Palindrome", "125", "https://leetcode.com/problems/valid-palindrome/", "Easy", "Two Pointers",
             "Skip non-alphanumeric characters while closing in from both ends."),
            ("Longest Common Prefix", "14", "https://leetcode.com/problems/longest-common-prefix/", "Easy", "Horizontal Scanning",
             "Trim a candidate prefix down each time it stops matching the next string."),
            ("Reverse String", "344", "https://leetcode.com/problems/reverse-string/", "Easy", "Two Pointers",
             "Swap characters from both ends moving toward the middle."),
            ("Reverse Words in a String", "151", "https://leetcode.com/problems/reverse-words-in-a-string/", "Medium", "Split & Reverse",
             "Trim and split on whitespace, then reverse the order of the resulting words."),
            ("Implement strStr()", "28", "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", "Easy", "Sliding Window",
             "Slide a window the length of the needle across the haystack and compare at each position."),
            ("Longest Palindromic Substring", "5", "https://leetcode.com/problems/longest-palindromic-substring/", "Medium", "Expand Around Center",
             "For each index, expand outward checking both odd- and even-length palindromes."),
            ("Longest Substring Without Repeating Characters", "3", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Medium", "Sliding Window",
             "Track seen characters in a set/map and shrink the window from the left on a duplicate."),
            ("Group Anagrams", "49", "https://leetcode.com/problems/group-anagrams/", "Medium", "Hash Map with Sorted Key",
             "Use each string's sorted form as a hash map key to bucket anagrams together."),
            ("Valid Parentheses", "20", "https://leetcode.com/problems/valid-parentheses/", "Easy", "Stack",
             "Push opening brackets; on a closing bracket, pop and check it matches."),
            ("String to Integer (atoi)", "8", "https://leetcode.com/problems/string-to-integer-atoi/", "Medium", "Manual Parsing",
             "Skip leading whitespace, handle an optional sign, consume digits, and clamp on overflow."),
            ("Integer to Roman", "12", "https://leetcode.com/problems/integer-to-roman/", "Medium", "Greedy Lookup Table",
             "Walk a value–symbol table from largest to smallest, subtracting greedily."),
            ("Roman to Integer", "13", "https://leetcode.com/problems/roman-to-integer/", "Easy", "Lookup Table",
             "Sum symbol values left to right, subtracting when a smaller value precedes a larger one."),
            ("Zigzag Conversion", "6", "https://leetcode.com/problems/zigzag-conversion/", "Medium", "Simulation",
             "Track which row each character lands on as you move down and back up the rows."),
            ("Minimum Window Substring", "76", "https://leetcode.com/problems/minimum-window-substring/", "Hard", "Sliding Window",
             "Expand the window until it covers the target, then shrink from the left to minimize it."),
            ("Find All Anagrams in a String", "438", "https://leetcode.com/problems/find-all-anagrams-in-a-string/", "Medium", "Sliding Window + Frequency Map",
             "Maintain a fixed-size window and compare its letter counts against the target's."),
            ("Isomorphic Strings", "205", "https://leetcode.com/problems/isomorphic-strings/", "Easy", "Two Hash Maps",
             "Map characters from s to t and t to s at the same time to enforce a one-to-one mapping both ways."),
            ("Word Pattern", "290", "https://leetcode.com/problems/word-pattern/", "Easy", "Two Hash Maps",
             "Map pattern letters to words and words back to pattern letters, checking both directions."),
            ("Decode String", "394", "https://leetcode.com/problems/decode-string/", "Medium", "Stack",
             "Push counts and partial strings onto a stack whenever you open a nested bracket."),
            ("Encode and Decode Strings", "", "", "Medium", "Length-Prefixing",
             "Prefix each string with its length and a delimiter so decoding can split them back apart unambiguously."),
        ],
    },
]
